#!/usr/bin/env node

/*
 * Posts accumulated-action checkbox items to the CRM inbox API.
 *
 * Feature notes:
 * Input is the actions-YYYY-MM-DD.md report generated by
 * scripts/build-accumulated-actions.js. The script writes one inbox payload per
 * checkbox action, deduped by a stable actionKey. It also reads the matching
 * removed-actions-YYYY-MM-DD.json file by default so Inbox can close stale work
 * items when local accumulated state retires them. Recent change: traceMarkdown
 * is an evidence trail only; judgment text stays in the separate insight,
 * tensions, and memory fields.
 */

const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
const { readMarkdown } = require('./layered-artifact-utils');

const workspaceRoot = path.resolve(__dirname, '..');
const envFilePath = path.join(workspaceRoot, '.env');
const postRoutePath = '/api/data/inbox';
const sourceMarkdownSectionMaxLength = 512;
const traceMarkdownMaxLength = 12000;
const traceTextMaxLength = 4000;

function parseEnvValue(rawValue) {
  const trimmed = rawValue.trim();
  if (!trimmed) {
    return '';
  }

  const quote = trimmed[0];
  if ((quote === '"' || quote === "'") && trimmed.endsWith(quote)) {
    const inner = trimmed.slice(1, -1);
    if (quote === '"') {
      return inner
        .replace(/\\n/g, '\n')
        .replace(/\\r/g, '\r')
        .replace(/\\t/g, '\t');
    }
    return inner;
  }

  const commentIndex = trimmed.indexOf(' #');
  if (commentIndex >= 0) {
    return trimmed.slice(0, commentIndex).trim();
  }

  return trimmed;
}

function loadDotEnv(filePath) {
  if (!fs.existsSync(filePath)) {
    return;
  }

  const lines = fs.readFileSync(filePath, 'utf8').split(/\r?\n/);
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) {
      continue;
    }

    const normalized = trimmed.startsWith('export ') ? trimmed.slice('export '.length) : trimmed;
    const equalsIndex = normalized.indexOf('=');
    if (equalsIndex <= 0) {
      continue;
    }

    const key = normalized.slice(0, equalsIndex).trim();
    if (!key || Object.prototype.hasOwnProperty.call(process.env, key)) {
      continue;
    }

    process.env[key] = parseEnvValue(normalized.slice(equalsIndex + 1));
  }
}

function getRequiredEnv(name) {
  const value = process.env[name];
  if (!value) {
    throw new Error(`Missing required environment variable: ${name}`);
  }
  return value;
}

function envFlagEnabled(name) {
  const value = String(process.env[name] || '').trim().toLowerCase();
  return value === '1' || value === 'true' || value === 'yes';
}

function requireWriteEnabled() {
  if (!envFlagEnabled('AIW_ENABLE_CRM_INBOX_POST')) {
    throw new Error('CRM inbox posting is disabled. Set AIW_ENABLE_CRM_INBOX_POST=1 to allow POST /api/data/inbox.');
  }
}

function printHelp() {
  console.log(`Usage:
  node scripts/post-inbox.js --dry-run
  node scripts/post-inbox.js --date=2026-05-20 --dry-run
  node scripts/post-inbox.js data/0/daily-triage/2026/05/20/actions-2026-05-20.md --dry-run
  node scripts/post-inbox.js --file=data/0/daily-triage/2026/05/20/actions-2026-05-20.md
  rg --files data | rg '^data/[0-9]+/daily-triage/2026/.+/actions-2026-.+\\.md$' | node scripts/post-inbox.js --files-from=- --dry-run

Options:
  --file PATH         Markdown file to read. Can be used multiple times.
  --files-from PATH   Read newline-delimited markdown file paths. Use - for stdin.
  --date YYYY-MM-DD   Daily triage date to import across all teams. Default: today.
  --include-checked   Include checked checkbox actions as status=done. Default: unchecked only.
  --skip-removed      Do not post same-day removed actions from removed-actions-YYYY-MM-DD.json.
  --status VALUE      Status for unchecked actions. Default: open.
  --strict-missing-team-link
                      Stop when account/contact validation fails for the mapped team. Default: skip and continue.
  --continue-on-error Continue after non-duplicate, non-team-link POST failures and report failed rows.
  --dry-run           Parse and print payloads without posting.
  --progress-every N  Print progress every N posted payloads. Default: 25.
  --quiet             Print only final counts.
  --json              Print JSON result instead of a compact summary.
  -h, --help          Show this help.

Environment:
  CRM_BASE_URL and CRM_ACCESS_TOKEN are required for posting.
  AIW_ENABLE_CRM_INBOX_POST=1 is required unless --dry-run is used.
`);
}

function parseArgs(argv) {
  const args = {
    filePaths: [],
    filesFrom: null,
    date: null,
    includeChecked: false,
    skipRemoved: false,
    status: 'open',
    skipMissingTeamLink: true,
    continueOnError: false,
    dryRun: false,
    json: false,
    quiet: false,
    progressEvery: 25,
    help: false,
  };

  for (let index = 0; index < argv.length; index += 1) {
    const part = argv[index];

    if (part === '--help' || part === '-h') {
      args.help = true;
      continue;
    }
    if (part === '--dry-run') {
      args.dryRun = true;
      continue;
    }
    if (part === '--json') {
      args.json = true;
      continue;
    }
    if (part === '--quiet') {
      args.quiet = true;
      continue;
    }
    if (part === '--include-checked') {
      args.includeChecked = true;
      continue;
    }
    if (part === '--skip-removed') {
      args.skipRemoved = true;
      continue;
    }
    if (part === '--skip-missing-team-link') {
      args.skipMissingTeamLink = true;
      continue;
    }
    if (part === '--strict-missing-team-link') {
      args.skipMissingTeamLink = false;
      continue;
    }
    if (part === '--continue-on-error') {
      args.continueOnError = true;
      continue;
    }
    if (part === '--file') {
      const value = argv[index + 1];
      if (!value) {
        throw new Error('Missing value after --file.');
      }
      args.filePaths.push(value);
      index += 1;
      continue;
    }
    if (part.startsWith('--file=')) {
      args.filePaths.push(part.slice('--file='.length));
      continue;
    }
    if (part === '--files-from') {
      const value = argv[index + 1];
      if (!value) {
        throw new Error('Missing value after --files-from.');
      }
      args.filesFrom = value;
      index += 1;
      continue;
    }
    if (part.startsWith('--files-from=')) {
      args.filesFrom = part.slice('--files-from='.length);
      continue;
    }
    if (part === '--date') {
      const value = argv[index + 1];
      if (!value) {
        throw new Error('Missing value after --date.');
      }
      args.date = value;
      index += 1;
      continue;
    }
    if (part.startsWith('--date=')) {
      args.date = part.slice('--date='.length);
      continue;
    }
    if (part === '--status') {
      const value = argv[index + 1];
      if (!value) {
        throw new Error('Missing value after --status.');
      }
      args.status = value;
      index += 1;
      continue;
    }
    if (part.startsWith('--status=')) {
      args.status = part.slice('--status='.length);
      continue;
    }
    if (part === '--progress-every') {
      const value = argv[index + 1];
      if (!value) {
        throw new Error('Missing value after --progress-every.');
      }
      args.progressEvery = parseProgressEvery(value);
      index += 1;
      continue;
    }
    if (part.startsWith('--progress-every=')) {
      args.progressEvery = parseProgressEvery(part.slice('--progress-every='.length));
      continue;
    }
    if (part.startsWith('-')) {
      throw new Error(`Unknown option: ${part}`);
    }
    args.filePaths.push(part);
  }

  if (args.filesFrom) {
    const list = args.filesFrom === '-'
      ? fs.readFileSync(0, 'utf8')
      : fs.readFileSync(path.resolve(workspaceRoot, args.filesFrom), 'utf8');
    args.filePaths.push(...list.split(/\r?\n/).map((line) => line.trim()).filter(Boolean));
  }

  if (args.date) {
    validateIsoDate(args.date, '--date');
  }
  if (!/^[A-Za-z0-9_-]+$/.test(args.status)) {
    throw new Error('--status must be a simple status value.');
  }

  return args;
}

function todayIso() {
  const now = new Date();
  const year = now.getFullYear();
  const month = String(now.getMonth() + 1).padStart(2, '0');
  const day = String(now.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
}

function parseProgressEvery(value) {
  const parsed = Number(value);
  if (!Number.isInteger(parsed) || parsed < 0) {
    throw new Error('--progress-every must be a non-negative integer.');
  }
  return parsed;
}

function validateIsoDate(value, label) {
  if (!/^\d{4}-\d{2}-\d{2}$/.test(value)) {
    throw new Error(`${label} must be YYYY-MM-DD.`);
  }
}

function compact(value) {
  return String(value || '').replace(/\s+/g, ' ').trim();
}

function truncate(value, maxLength) {
  const text = String(value || '').trim();
  if (text.length <= maxLength) {
    return text;
  }
  return text.slice(0, maxLength - 1).trimEnd();
}

function toRelativePath(filePath) {
  return path.relative(workspaceRoot, filePath).split(path.sep).join('/');
}

function inferDate(markdown, inputPath, overrideDate) {
  if (overrideDate) {
    return overrideDate;
  }

  const asOfMatch = markdown.match(/^- As-of date:\s*(\d{4}-\d{2}-\d{2})\s*$/m);
  if (asOfMatch) {
    return asOfMatch[1];
  }

  if (inputPath) {
    const filenameMatch = path.basename(inputPath).match(/actions-(\d{4}-\d{2}-\d{2})\.md$/);
    if (filenameMatch) {
      return filenameMatch[1];
    }
  }

  throw new Error('Could not infer date. Pass --date=YYYY-MM-DD.');
}

function dateParts(isoDate) {
  return {
    year: isoDate.slice(0, 4),
    month: isoDate.slice(5, 7),
    day: isoDate.slice(8, 10),
  };
}

function defaultFilesForDate(isoDate) {
  const { year, month, day } = dateParts(isoDate);
  const dataRoot = path.join(workspaceRoot, 'data');
  const filePaths = [];

  if (!fs.existsSync(dataRoot)) {
    return filePaths;
  }

  for (const entry of fs.readdirSync(dataRoot, { withFileTypes: true })) {
    if (!entry.isDirectory() || !/^-?\d+$/.test(entry.name)) {
      continue;
    }

    const candidate = path.join(dataRoot, entry.name, 'daily-triage', year, month, day, `actions-${isoDate}.md`);
    if (fs.existsSync(candidate)) {
      filePaths.push(toRelativePath(candidate));
    }
  }

  return filePaths.sort();
}

function inferWorkspaceTeamId(inputPath) {
  const relativePath = toRelativePath(inputPath);
  const match = relativePath.match(/^data\/(-?\d+)\/daily-triage\/\d{4}\/\d{2}\/\d{2}\/actions-\d{4}-\d{2}-\d{2}\.md$/);
  if (!match) {
    throw new Error(`Could not infer teamId from path: ${relativePath}`);
  }
  return Number(match[1]);
}

function apiTeamIdFromWorkspaceTeam(workspaceTeamId) {
  const teamId = Number(workspaceTeamId);
  return teamId === -1 || teamId === 0 ? 8 : teamId;
}

function inferTeamId(inputPath) {
  return apiTeamIdFromWorkspaceTeam(inferWorkspaceTeamId(inputPath));
}

function parseObjectKey(line) {
  const match = line.match(/^- (Account|Contact) key:\s*(account|contact):(\d+)\s*$/i);
  if (!match) {
    return null;
  }
  return {
    objectType: match[2].toLowerCase(),
    objectId: Number(match[3]),
  };
}

function parseSectionDate(line, label) {
  const match = line.match(new RegExp(`^- ${label}:\\s*(\\d{4}-\\d{2}-\\d{2}|unknown)\\s*$`, 'i'));
  if (!match || match[1] === 'unknown') {
    return null;
  }
  return match[1];
}

function parseActionLine(line) {
  const match = line.match(/^- \[([ xX])\]\s+(.+)$/);
  if (!match) {
    return null;
  }

  const actionText = compact(match[2]);
  if (!actionText) {
    return null;
  }

  return {
    checked: match[1].toLowerCase() === 'x',
    actionText,
  };
}

function normalizeActionText(value) {
  return compact(value)
    .toLowerCase()
    .replace(/[“”]/g, '"')
    .replace(/[‘’]/g, "'");
}

function makeActionKey(teamId, objectType, objectId, actionText) {
  const normalized = normalizeActionText(actionText);
  const fullKey = `${teamId}:${objectType}:${objectId}:${normalized}`;
  if (fullKey.length <= 256) {
    return fullKey;
  }

  const digest = crypto.createHash('sha256').update(fullKey).digest('hex').slice(0, 24);
  const prefix = `${teamId}:${objectType}:${objectId}:`;
  const maxTextLength = 256 - prefix.length - digest.length - 1;
  return `${prefix}${normalized.slice(0, Math.max(0, maxTextLength))}:${digest}`;
}

function actionLookupKey(teamId, objectType, objectId, actionText) {
  return `${teamId}:${objectType}:${objectId}:${normalizeActionText(actionText)}`;
}

function compactMarkdownLines(lines) {
  return (lines || [])
    .join('\n')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

function subsectionText(section, subsectionName) {
  const normalized = subsectionName.toLowerCase();
  const key = Object.keys(section.subsections).find((candidate) => candidate.toLowerCase() === normalized);
  return key ? compactMarkdownLines(section.subsections[key]) : '';
}

function absoluteWorkspacePath(relativePath) {
  if (!relativePath) {
    return null;
  }
  return path.join(workspaceRoot, String(relativePath).split('/').join(path.sep));
}

function siblingDailyTriagePath(inputPath, filename) {
  return path.join(path.dirname(inputPath), filename);
}

function accumulatedActionsPathForInput(inputPath, isoDate) {
  return siblingDailyTriagePath(inputPath, `accumulated-actions-${isoDate}.json`);
}

function removedActionsPathForInput(inputPath, isoDate) {
  return siblingDailyTriagePath(inputPath, `removed-actions-${isoDate}.json`);
}

function readJsonIfExists(filePath) {
  if (!fs.existsSync(filePath)) {
    return null;
  }
  return JSON.parse(fs.readFileSync(filePath, 'utf8'));
}

function activeActionMetadataByKey(inputPath, isoDate) {
  const snapshot = readJsonIfExists(accumulatedActionsPathForInput(inputPath, isoDate));
  const rows = snapshot && Array.isArray(snapshot.active_actions) ? snapshot.active_actions : [];
  const metadata = new Map();
  for (const row of rows) {
    const actionText = compact(row.action_text);
    if (!row.object_type || !row.object_id || !actionText) {
      continue;
    }
    metadata.set(actionLookupKey(row.team_id, row.object_type, row.object_id, actionText), {
      latestSummaryPath: row.latest_summary_path || null,
      evidenceDate: row.source_date || null,
    });
  }
  return metadata;
}

function parseActionsReportSections(markdown) {
  const sections = [];
  let section = null;
  let subsection = null;

  for (const rawLine of markdown.split(/\r?\n/)) {
    const line = rawLine.trimEnd();
    const trimmed = line.trim();

    if (/^###\s+/.test(trimmed)) {
      section = {
        heading: trimmed,
        lines: [trimmed],
        object: null,
        firstSeenDate: null,
        lastSeenDate: null,
        sourceDate: null,
        subsections: {},
      };
      sections.push(section);
      subsection = null;
      continue;
    }

    if (!section) {
      continue;
    }

    section.lines.push(line);

    const object = parseObjectKey(trimmed);
    if (object) {
      section.object = object;
      continue;
    }

    section.firstSeenDate = section.firstSeenDate || parseSectionDate(trimmed, 'First seen');
    section.lastSeenDate = section.lastSeenDate || parseSectionDate(trimmed, 'Last seen');
    section.sourceDate = section.sourceDate || parseSectionDate(trimmed, 'Source date');

    const subsectionMatch = trimmed.match(/^####\s+(.+?)\s*$/);
    if (subsectionMatch) {
      subsection = subsectionMatch[1];
      section.subsections[subsection] = [];
      continue;
    }

    if (subsection) {
      section.subsections[subsection].push(line);
    }
  }

  return sections;
}

function sourceMarkdownPreview(section, objectType, objectId, actionLine) {
  return truncate([
    section.heading,
    objectType === 'account' ? `- Account key: account:${objectId}` : `- Contact key: contact:${objectId}`,
    '#### Actions',
    actionLine,
  ].join('\n'), sourceMarkdownSectionMaxLength);
}

function traceFieldsForSection(section) {
  const insightText = truncate(subsectionText(section, 'Insight'), traceTextMaxLength);
  const tensionsText = truncate(subsectionText(section, 'Tensions'), traceTextMaxLength);
  const memoryText = truncate(subsectionText(section, 'Memory'), traceTextMaxLength);
  return {
    insightText,
    tensionsText,
    memoryText,
  };
}

function activeTraceMarkdown(section, objectType, objectId, actionLine, metadata, sourceActionsReportPath) {
  const evidenceDate = metadata.evidenceDate || section.sourceDate || null;
  return truncate([
    `### Evidence trail for ${objectType}:${objectId}`,
    '',
    objectType === 'account' ? `- Account key: account:${objectId}` : `- Contact key: contact:${objectId}`,
    `- First seen: ${section.firstSeenDate || 'unknown'}`,
    `- Last seen: ${section.lastSeenDate || 'unknown'}`,
    `- Source date: ${section.sourceDate || 'unknown'}`,
    `- Evidence date: ${evidenceDate || 'unknown'}`,
    `- Source actions report: ${sourceActionsReportPath}`,
    '',
    '#### Action item',
    '',
    actionLine,
  ].join('\n'), traceMarkdownMaxLength);
}

function parseInboxPayloads(markdown, inputPath, args) {
  const workspaceTeamId = inferWorkspaceTeamId(inputPath);
  const teamId = inferTeamId(inputPath);
  const asOfDate = inferDate(markdown, inputPath, args.importDate);
  const sourcePath = toRelativePath(inputPath);
  const activeMetadata = activeActionMetadataByKey(inputPath, asOfDate);
  const payloads = [];
  const seen = new Set();

  for (const section of parseActionsReportSections(markdown)) {
    if (!section.object) {
      continue;
    }

    const objectType = section.object.objectType;
    const objectId = section.object.objectId;
    const traceFields = traceFieldsForSection(section);

    for (const actionLine of section.subsections.Actions || []) {
      const parsedAction = parseActionLine(actionLine.trim());
      if (!parsedAction || (parsedAction.checked && !args.includeChecked)) {
        continue;
      }

      const actionKey = makeActionKey(teamId, objectType, objectId, parsedAction.actionText);
      if (seen.has(actionKey)) {
        continue;
      }
      seen.add(actionKey);

      const metadata = activeMetadata.get(actionLookupKey(workspaceTeamId, objectType, objectId, parsedAction.actionText)) || {};
      const trimmedActionLine = actionLine.trim();

      payloads.push({
        teamId,
        accountId: objectType === 'account' ? objectId : null,
        contactId: objectType === 'contact' ? objectId : null,
        sourceDate: asOfDate,
        evidenceDate: metadata.evidenceDate || section.sourceDate,
        actionText: parsedAction.actionText,
        status: parsedAction.checked ? 'done' : args.status,
        firstSeenDate: section.firstSeenDate,
        lastSeenDate: section.lastSeenDate,
        removedDate: null,
        removalReason: null,
        sourcePath,
        sourceActionsReportPath: sourcePath,
        sourceSummaryPath: metadata.latestSummaryPath || null,
        sourceMarkdownSection: sourceMarkdownPreview(section, objectType, objectId, trimmedActionLine),
        actionKey,
        traceMarkdown: activeTraceMarkdown(section, objectType, objectId, trimmedActionLine, metadata, sourcePath),
        ...traceFields,
      });
    }
  }

  return payloads;
}

function statusForRemovalReason(reason) {
  switch (reason) {
    case 'checked-or-completed':
      return 'done';
    case 'not-present-in-latest-action':
      return 'superseded';
    case 'no-supported-actions-in-summary':
      return 'no_longer_supported';
    case 'closed-status':
      return 'removed';
    default:
      return 'removed';
  }
}

function readSummaryTrace(summaryPath) {
  const absolutePath = absoluteWorkspacePath(summaryPath);
  if (!absolutePath || !fs.existsSync(absolutePath)) {
    return {
      insightText: '',
      tensionsText: '',
      memoryText: '',
    };
  }

  const markdown = readMarkdown(absolutePath);
  return {
    insightText: truncate(compactMarkdownLines(markdown.sections.Insight || []), traceTextMaxLength),
    tensionsText: truncate(compactMarkdownLines(markdown.sections.Tensions || []), traceTextMaxLength),
    memoryText: truncate(compactMarkdownLines(markdown.sections.Memory || []), traceTextMaxLength),
  };
}

function removedTraceMarkdown(action, sourcePath, sourceActionsReportPath) {
  const objectType = action.object_type;
  const objectId = action.object_id;
  return truncate([
    `### Evidence trail for removed ${objectType}:${objectId}`,
    '',
    `- ${objectType === 'account' ? 'Account' : 'Contact'} key: ${objectType}:${objectId}`,
    `- First seen: ${action.first_seen_date || 'unknown'}`,
    `- Last seen: ${action.last_seen_date || 'unknown'}`,
    `- Source date: ${action.source_date || 'unknown'}`,
    `- Removed date: ${action.removed_date || 'unknown'}`,
    `- Removal reason: ${action.removal_reason || 'unknown'}`,
    `- Removed actions file: ${sourcePath}`,
    `- Source actions report: ${sourceActionsReportPath}`,
    '',
    '#### Action item',
    '',
    `- [x] ${compact(action.action_text)}`,
  ].join('\n'), traceMarkdownMaxLength);
}

function removedSourceMarkdownPreview(action) {
  const objectType = action.object_type;
  const objectId = action.object_id;
  return truncate([
    `### Removed ${objectType}:${objectId}`,
    objectType === 'account' ? `- Account key: account:${objectId}` : `- Contact key: contact:${objectId}`,
    `- Removed date: ${action.removed_date || 'unknown'}`,
    `- Removal reason: ${action.removal_reason || 'unknown'}`,
    '#### Actions',
    `- [x] ${compact(action.action_text)}`,
  ].join('\n'), sourceMarkdownSectionMaxLength);
}

function parseRemovedPayloadItems(inputPath, args) {
  if (args.skipRemoved) {
    return [];
  }

  const asOfDate = args.importDate || inferDate('', inputPath, null);
  const removedPath = removedActionsPathForInput(inputPath, asOfDate);
  const removed = readJsonIfExists(removedPath);
  if (!removed || !Array.isArray(removed.removed_actions)) {
    return [];
  }

  const workspaceTeamId = inferWorkspaceTeamId(inputPath);
  const teamId = apiTeamIdFromWorkspaceTeam(workspaceTeamId);
  const sourceActionsReportPath = toRelativePath(inputPath);
  const sourcePath = toRelativePath(removedPath);
  const items = [];
  const seen = new Set();

  for (const action of removed.removed_actions) {
    const objectType = action.object_type;
    const objectId = Number(action.object_id);
    const actionText = compact(action.action_text);
    if (!objectType || !objectId || !actionText) {
      continue;
    }

    const actionKey = makeActionKey(teamId, objectType, objectId, actionText);
    if (seen.has(actionKey)) {
      continue;
    }
    seen.add(actionKey);

    const traceFields = readSummaryTrace(action.latest_summary_path);
    items.push({
      inputPath: removedPath,
      payload: {
        teamId,
        accountId: objectType === 'account' ? objectId : null,
        contactId: objectType === 'contact' ? objectId : null,
        sourceDate: action.removed_date || asOfDate,
        evidenceDate: action.source_date || null,
        actionText,
        status: statusForRemovalReason(action.removal_reason),
        firstSeenDate: action.first_seen_date || null,
        lastSeenDate: action.last_seen_date || null,
        removedDate: action.removed_date || asOfDate,
        removalReason: action.removal_reason || 'removed',
        sourcePath,
        sourceActionsReportPath,
        sourceSummaryPath: action.latest_summary_path || null,
        sourceMarkdownSection: removedSourceMarkdownPreview(action),
        actionKey,
        traceMarkdown: removedTraceMarkdown(action, sourcePath, sourceActionsReportPath),
        ...traceFields,
      },
    });
  }

  return items;
}

function buildPayloadsForFiles(args) {
  const payloads = [];
  for (const filePath of args.filePaths) {
    const inputPath = path.resolve(workspaceRoot, filePath);
    const markdown = fs.readFileSync(inputPath, 'utf8');
    for (const payload of parseInboxPayloads(markdown, inputPath, args)) {
      payloads.push({
        payload,
        inputPath,
      });
    }
    payloads.push(...parseRemovedPayloadItems(inputPath, args));
  }
  return payloads;
}

function buildUrl(baseUrl, routePath) {
  return new URL(routePath.replace(/^\//, ''), `${baseUrl.replace(/\/+$/, '')}/`);
}

function authHeader(token) {
  return /^Bearer\s+/i.test(token) ? token : `Bearer ${token}`;
}

function printProgress(label, current, total, args) {
  if (args.quiet || args.progressEvery === 0) {
    return;
  }
  if (current === total || current % args.progressEvery === 0) {
    console.error(`${label}: ${current}/${total}`);
  }
}

async function postInboxItem(baseUrl, token, payload) {
  const response = await fetch(buildUrl(baseUrl, postRoutePath), {
    method: 'POST',
    headers: {
      Authorization: authHeader(token),
      Accept: 'application/json',
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(payload),
  });

  const responseText = await response.text();
  let body = responseText;
  if (responseText) {
    try {
      body = JSON.parse(responseText);
    } catch {
      body = responseText;
    }
  }

  if (!response.ok && isDuplicateInboxError(responseText)) {
    return {
      status: response.status,
      body,
      skippedDuplicate: true,
    };
  }

  if (!response.ok) {
    throw new Error(`POST ${postRoutePath} failed (${response.status} ${response.statusText}): ${responseText.slice(0, 500)}`);
  }

  return {
    status: response.status,
    body,
    skippedDuplicate: false,
  };
}

function isDuplicateInboxError(responseText) {
  return /Cannot insert duplicate key row/i.test(responseText)
    && /UX_Inbox_TeamId_ActionKey/i.test(responseText);
}

function isMissingTeamLinkError(error) {
  return /Account not found for team|Contact not found for team/i.test(String(error && error.message ? error.message : error));
}

function shouldFailDuplicate(payload, args) {
  return payload.status !== args.status || Boolean(payload.removalReason || payload.removedDate);
}

function failedPayloadDetail(item, index, total, error) {
  return {
    index: index + 1,
    total,
    inputPath: toRelativePath(item.inputPath),
    teamId: item.payload.teamId,
    accountId: item.payload.accountId,
    contactId: item.payload.contactId,
    sourceDate: item.payload.sourceDate,
    status: item.payload.status,
    actionKey: item.payload.actionKey,
    error: error.message || String(error),
  };
}

async function postInboxItems(baseUrl, token, payloads, args) {
  const results = [];
  const skippedDuplicates = [];
  const skippedMissingTeamLinks = [];
  const failed = [];
  for (let index = 0; index < payloads.length; index += 1) {
    const item = payloads[index];
    let result;
    try {
      result = await postInboxItem(baseUrl, token, item.payload);
    } catch (error) {
      if (args.skipMissingTeamLink && isMissingTeamLinkError(error)) {
        skippedMissingTeamLinks.push({
          inputPath: item.inputPath,
          payload: item.payload,
          error: error.message || String(error),
        });
        printProgress('Processed inbox items', index + 1, payloads.length, args);
        continue;
      }

      if (!result) {
        const detail = failedPayloadDetail(item, index, payloads.length, error);
        if (args.continueOnError) {
          failed.push(detail);
          printProgress('Processed inbox items', index + 1, payloads.length, args);
          continue;
        }
        throw new Error(`${error.message || error}\nFailed inbox payload: ${JSON.stringify(detail)}`);
      }
    }
    const row = {
      payload: item.payload,
      inputPath: item.inputPath,
      ...result,
    };
    if (result.skippedDuplicate) {
      if (shouldFailDuplicate(item.payload, args)) {
        const error = new Error('Backend rejected a duplicate non-open Inbox status. The Inbox route must upsert by actionKey to close or supersede stale work.');
        const detail = failedPayloadDetail(item, index, payloads.length, error);
        if (args.continueOnError) {
          failed.push(detail);
          printProgress('Processed inbox items', index + 1, payloads.length, args);
          continue;
        }
        throw new Error(`${error.message}\nFailed inbox payload: ${JSON.stringify(detail)}`);
      }
      skippedDuplicates.push(row);
    } else {
      results.push(row);
    }
    printProgress('Processed inbox items', index + 1, payloads.length, args);
  }
  return { results, skippedDuplicates, skippedMissingTeamLinks, failed };
}

function summarizePayload(payload) {
  const target = payload.accountId ? `account:${payload.accountId}` : `contact:${payload.contactId}`;
  const removal = payload.removalReason ? ` (${payload.removalReason})` : '';
  return `${target} ${payload.sourceDate} ${payload.status}${removal} - ${payload.actionText}`;
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  if (args.help) {
    printHelp();
    return;
  }

  args.importDate = args.date || todayIso();
  if (args.filePaths.length === 0) {
    args.filePaths = defaultFilesForDate(args.importDate);
    if (args.filePaths.length === 0) {
      throw new Error(`No action files found for ${args.importDate}. Pass --date=YYYY-MM-DD or --file PATH.`);
    }
  }

  const payloads = buildPayloadsForFiles(args);
  if (payloads.length === 0) {
    if (args.json) {
      console.log(JSON.stringify({
        dry_run: args.dryRun,
        route: postRoutePath,
        count: 0,
        payloads: [],
      }, null, 2));
    } else {
      console.log(`No inbox payloads found for ${args.importDate}.`);
    }
    return;
  }

  if (args.dryRun) {
    if (args.json) {
      console.log(JSON.stringify({
        dry_run: true,
        route: postRoutePath,
        count: payloads.length,
        payloads: payloads.map((item) => ({
          input_path: toRelativePath(item.inputPath),
          ...item.payload,
        })),
      }, null, 2));
      return;
    }

    console.log(`Dry run: parsed ${payloads.length} inbox payloads for POST ${postRoutePath}.`);
    if (!args.quiet) {
      for (const item of payloads) {
        console.log(`- ${summarizePayload(item.payload)}`);
      }
    }
    return;
  }

  loadDotEnv(envFilePath);
  requireWriteEnabled();
  const baseUrl = getRequiredEnv('CRM_BASE_URL');
  const token = getRequiredEnv('CRM_ACCESS_TOKEN');
  const { results, skippedDuplicates, skippedMissingTeamLinks, failed } = await postInboxItems(baseUrl, token, payloads, args);

  if (args.json) {
    console.log(JSON.stringify({
      dry_run: false,
      route: postRoutePath,
      posted: results.length,
      skipped_duplicates: skippedDuplicates.length,
      skipped_missing_team_links: skippedMissingTeamLinks.length,
      failed: failed.length,
      results: results.map((result) => ({
        ...result,
        inputPath: toRelativePath(result.inputPath),
      })),
      failed_items: failed,
    }, null, 2));
    if (failed.length > 0) {
      process.exitCode = 1;
    }
    return;
  }

  console.log(`Posted ${results.length} inbox payloads to ${postRoutePath}.`);
  console.log(`Skipped ${skippedDuplicates.length} duplicate inbox payloads.`);
  console.log(`Skipped ${skippedMissingTeamLinks.length} inbox payloads after team validation failures.`);
  console.log(`Failed ${failed.length} inbox payloads.`);
  if (failed.length > 0) {
    for (const item of failed) {
      console.log(`- failed index ${item.index}/${item.total}: team:${item.teamId} ${item.accountId ? `account:${item.accountId}` : `contact:${item.contactId}`} ${item.sourceDate} ${item.error}`);
    }
    process.exitCode = 1;
  }
}

if (require.main === module) {
  main().catch((error) => {
    console.error(error.message || error);
    process.exitCode = 1;
  });
}

module.exports = {
  parseActionsReportSections,
  parseInboxPayloads,
  parseRemovedPayloadItems,
  buildPayloadsForFiles,
  makeActionKey,
  statusForRemovalReason,
};
